name: Build Flet macOS App
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened

env:
  UV_PYTHON: 3.13

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Build app
        run: uv run flet build macos --yes --verbose

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app_macOS_${{ github.sha }}.zip
          path: build/macos/*
